apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-1
  labels:
    app: flask1
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask1
  template:
    metadata:
      labels:
        app: flask1
    spec:
      containers:
        - name: flask1
          image: {{ .Values.flask1.image.repository }}:{{ .Values.flask1.image.tag }} 
          ports:
            - containerPort: 5000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_name
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_pwd
            - name: DB_URL
              value: {{ .Values.db_url }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-2
  labels:
    app: flask2
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask2
  template:
    metadata:
      labels:
        app: flask2
    spec:
      containers:
        - name: flask2
          image: {{ .Values.flask2.image.repository }}:{{ .Values.flask2.image.tag }}
          ports:
            - containerPort: 5000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_name
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_pwd
            - name: DB_URL
              value: {{ .Values.db_url }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-3
  labels:
    app: flask3
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask3
  template:
    metadata:
      labels:
        app: flask3
    spec:
      containers:
        - name: flask3
          image: {{ .Values.flask3.image.repository }}:{{ .Values.flask3.image.tag }}
          ports:
            - containerPort: 5000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_name
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_pwd
            - name: DB_URL
              value: {{ .Values.db_url }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/local/apache2/htdocs
      volumes:
        - name: html-volume
          configMap:
            name: prod-html-configmap
            items: 
              - key: index.html
                path: index.html



