apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-1 
  labels:
    app: flask1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask1
  template:
    metadata:
      labels:
        app: flask1
    spec:
      containers:
        - name: flask1
          image: {{ .Values.flask1.image.repository }}:{{ .Values.flask1.image.tag }}
          ports:
            - containerPort: 5000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_name
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_pwd
            - name: DB_URL
              value: {{ .Values.db_url }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-2
  labels:
    app: flask2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask2
  template:
    metadata:
      labels:
        app: flask2
    spec:
      containers:
        - name: flask2
          image: {{ .Values.flask2.image.repository }}:{{ .Values.flask2.image.tag }}
          ports:
            - containerPort: 5000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_name
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_pwd
            - name: DB_URL
              value: {{ .Values.db_url }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-3
  labels:
    app: flask3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask3
  template:
    metadata:
      labels:
        app: flask3
    spec:
      containers:
        - name: flask3
          image: {{ .Values.flask3.image.repository }}:{{ .Values.flask3.image.tag }}
          ports:
            - containerPort: 5000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_name
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: user_pwd
            - name: DB_URL
              value: {{ .Values.db_url }}
              
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-html-configmap
data:
  index.html: |
    <html>
    <head>
        <title>Daniel Gifs Website</title>
        <style>
            body {
                background-color: #f2f2f2;
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
            }

            section {
                background-color: #fff;
                padding: 20px;
                margin-bottom: 20px;
            }

            button {
                background-color: #4CAF50;
                border: none;
                color: white;
                padding: 10px 20px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                cursor: pointer;
            }

            header {
                background-color: #333;
                padding: 20px;
                color: #fff;
            }

            nav ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
            }

            nav ul li {
                display: inline;
            }

            nav ul li a {
                color: #fff;
                padding: 10px;
                text-decoration: none;
            }

            nav ul li a:hover {
                background-color: #555;
            }

            header h1 {
                margin: 0;
            }

            p {
                margin: 10px 0;
            }
        </style>
    </head>
    <body>
        <header>
            <h1>Welcome to Daniel Gifs Website</h1>
            <nav>
                <ul>
                    <li><a href="#dogs">Dogs Gifs</a></li>
                    <li><a href="#alpacas">Classmates Gifs</a></li>
                    <li><a href="#classmates">Alpacas Gifs</a></li>
                </ul>
            </nav>
        </header> 

        <section id="dogs">
            <h2>Dogs Gifs</h2>
            <p>Click the button below to explore Dogs Gifs:</p>
            <button onclick="window.location.href='http//34.31.106.119:5000'">Explore Dogs Gifs</button>
        </section>

        <section id="classmates">
            <h2>Classmates Gifs</h2>
            <p>Click the button below to explore Classmates Gifs:</p>
            <button onclick="window.location.href='http//34.170.154.176:5000''">Explore Classmates Gifs</button>
        </section>

        <section id="alpacas">-
            <h2>Alpacas Gifs</h2>
            <p>Click the button below to explore Alpacas Gifs:</p>
            <button onclick="window.location.href='http//35.224.239.186:5000''">Explore Alpacas Gifs</button>
        </section>

        <footer>
            <p>&copy; 2023 Daniel Gifs Website. All rights reserved.</p>
        </footer>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/local/apache2/htdocs
      volumes:
        - name: html-volume
          configMap:
            name: prod-html-configmap
            items:
              - key: index.html
                path: index.html