apiVersion: v1
kind: Service
metadata:
  name: flask-service-1
spec:
  selector:
    app: flask-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer


---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-2
spec:
  selector:
    app: flask-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer


---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-3
spec:
  selector:
    app: flask-3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: prod-httpd-service
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

