apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  rules:
    - http:
        paths:
          - path: /flask1
            pathType: Prefix
            backend:
              service:
                name: flask-service-1
                port:
                  number: 81  
          - path: /flask2
            pathType: Prefix
            backend:
              service:
                name: flask-service-2
                port:
                  number: 82
          - path: /flask3
            pathType: Prefix
            backend:
              service:
                name: flask-service-3
                port:
                  number: 83

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-1
spec:
  type: LoadBalancer
  selector:
    app: flask-1
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-2
spec:
  type: LoadBalancer
  selector:
    app: flask-2
  ports:
    - protocol: TCP
      port: 82
      targetPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-3
spec:
  type: LoadBalancer
  selector:
    app: flask-3
  ports:
    - protocol: TCP
      port: 83
      targetPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: prod-httpd-service
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
