apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  labels:
spec:
  rules:
    - http:
        paths:
          - path: /flask-1
            pathType: Prefix
            backend:
              service:
                name: flask-service-1
                port:
                  number: 5001
          - path: /flask-2
            pathType: Prefix
            backend:
              service:
                name: flask-service-2
                port:
                  number: 5002
          - path: /flask-3
            pathType: Prefix
            backend:
              service:
                name: flask-service-3
                port:
                  number: 5003

apiVersion: v1
kind: Service
metadata:
  name: flask-service-1
spec:
  type: LoadBalancer
  selector:
    app: flask-1
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-2
spec:
  type: LoadBalancer
  selector:
    app: flask-2
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-3
spec:
  type: LoadBalancer
  selector:
    app: flask-3
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: prod-httpd-service
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
