name: Gifs-Website

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  GKE_REGION: 'us-central1'
  PROJECT_ID: 'lofty-dynamics-393510'

jobs:
  Versioning-Images:
    name: Versioning Application Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Flask-1 Image   
        run: >
          pip3 install docker;
          python3 manageVersion.py;
          echo 'Build and Push Flask-1 Image Stage Completed'
        working-directory: App/Flask-Project

      - name: Build and Push Flask-2 Image
        run: >
          python3 manageVersion.py;
          echo 'Build and Push Flask-2 Image Stage Completed'
        working-directory: App/Flask-Project2

      - name: Build and Push Flask-3 Image
        run: >
          python3 manageVersion.py;
          echo 'Build and Push Flask-3 Image Stage Completed'
        working-directory: App/Flask-Project3

  GKE-Setup-Testing-Cluster:
    name: Setup the GKE-Testing-Cluster
    needs: [Versioning-Images]
    runs-on: ubuntu-latest
    env:
      GKE_CLUSTER: "gifs-website-test"
      GKE_REGION: "us-central1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup GCloud CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIAL }}
      - name: Retrieve cluster info for use with kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
            cluster_name: "gifs-website-test"
            location: "us-central1"
          
      - name: Install jq
        run: sudo apt install jq -y
        working-directory: charts-prod
          
      - name: Modify values.yml with secret
        run: sed -i "s|\$DEV_RDS_CREDS_U|${{ secrets.RDS_CREDS }}|" values.yml
        working-directory: charts-prod

      - name: Modify values.yml with secret
        run: sed -i "s|\$DEV_RDS_CREDS_P|${{ secrets.RDS_CREDS }}|" values.yml
        working-directory: charts-prod
          
      - name: Run changeValues.sh
        run: >
          chmod +x changeValues.sh && bash changeValues.sh
        working-directory: charts-prod
          
      - name: Deploy to Testing Env GCP Cluster
        run: >
          chmod 600 /home/runner/work/Gifs-Website/Gifs-Website/gha-kubeconfig-83b3fe6b15653b51
          kubectl config use-context gke_lofty-dynamics-393510_us-central1_gifs-website-test;
          helm upgrade --install gifs-website-westing . -f values.yml; 
          echo 'Deploy Application into Rancher Desktop Completed';
        working-directory: charts-prod
        
  Test-Testing-Cluster:
    name: Testing Test-Cluster
    runs-on: ubuntu-latest
    needs: [GKE-Setup-Testing-Cluster]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test Testing Server
        run: >
          bash test.sh;
          echo Testing Test-Server Stage Completed;
        working-directory: tests

  GKE-Setup-Production-Cluster:
    name: Setup the GKE-Prod-Cluster
    needs: [Test-Testing-Cluster]
    runs-on: ubuntu-latest
    env:
      GKE_CLUSTER: "gifs-website-prod"
      GKE_REGION: "us-central1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup GCloud CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIAL }}
      - name: Retrieve cluster info for use with kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
            cluster_name: "gifs-website-prod"
            location: "us-central1"
      - name: Activate GCP Service Account
        run: >
          sudo apt install jq -y; 
          sed -i "s|\$DEV_RDS_CREDS|${{ secrets.RDS_CREDS }}|"   
        working-directory: charts-prod

      - name: Deploy to Production Env GCP Cluster
        run: >
          chmod 600 /home/runner/work/Gifs-Website/Gifs-Website/gha-kubeconfig-83b3fe6b15653b51
          helm install my-release path/to/your/helm/chart -f path/to/your/values.yml
          kubectl config use-context gke_lofty-dynamics-393510_us-central1_gifs-website-prod; 
          bash changeTagflask.sh danielpinhas/flask-k8s;
          bash changeTagflask.sh danielpinhas/flask2-k8s;
          bash changeTagflask.sh danielpinhas/flask3-k8s;
          kubectl apply -f service-html.yml;
          kubectl apply -f flask-prod.yml;
          kubectl apply -f httpd-deploy-prod.yml;
          echo 'Deploy Application into Production GCP Cluster Completed';
        working-directory: charts-prod

  Test-Production-Server:
    name: Testing Prod-Server
    runs-on: ubuntu-latest
    needs: [GKE-Setup-Production-Cluster]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test Production Server
        run: >
          bash ingressIP.sh;
          bash prod.sh;
          echo 'Testing Prod-Server Stage Completed';
        working-directory: tests