name: Gifs-Website

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate cred.json
      uses: frdrwrt/write-to-file@v1.3
      with:
        filepath: Gifs-Website/Terraform-Autopilot/cred.json
        content: ${{secrets.GCP_CREDENTIAL}}
        mode: 744

    - name: Dependncies
      run: >
        pip3 install docker
        export GOOGLE_APPLICATION_CREDENTIALS="Gifs-Website/Terraform-Autopilot/cred.json"

    - name: Updating Changes
      run: >
        cd ~ && sudo rm -rf Gifs-Website || true;  
        cd ~ && git clone https://github.com/Daniel-Pinhas/Gifs-Website.git;


    - name: Build and Push Flask-1 Image
      run: >
        cd ~/Gifs-Website/App/Flask-Project && python3 manageVersion.py;
        echo 'Build and Push Flask-1 Image Stage Completed';

    - name: Build and Push Flask-2 Image
      run: >
        cd ~/Gifs-Website/App/Flask-Project2 && python3 manageVersion.py;
        echo 'Build and Push Flask-2 Image Stage Completed';

    - name: Build and Push Flask-3 Image
      run: >
        cd ~/Gifs-Website/App/Flask-Project3 && python3 manageVersion.py;
        echo 'Build and Push Flask-3 Image Stage Completed';

    - name: Deploy to Testing Env GCP Cluster
      run: > 
        gcloud container clusters get-credentials gifs-website-test --region us-central1 --project lofty-dynamics-393510
        kubectl config set-context gke_lofty-dynamics-393510_us-central1_gifs-website-test;
        cd charts-prod && bash changeTagflask.sh;
        cd charts-prod && kubectl apply -f service-html.yml;
        cd charts-prod && kubectl apply -f flask-prod.yml;
        sleep 60;
        cd charts-prod && bash updateHTML.sh;
        cd charts-prod && kubectl apply -f httpd-deploy-prod.yml;
        echo 'Deploy Application into Rancher Desktop Completed';

    - name: Testing Test-Server
      run: >
        cd tests && bash ingressIP.sh;
        cd tests && bash test.sh;
        echo Testing Test-Server Stage Completed;

    - name: Deploy to Production Env GCP Cluster
      run: >
        gcloud container clusters get-credentials gifs-website-prod --region us-central1 --project lofty-dynamics-393510
        kubectl config set-context gke_lofty-dynamics-393510_us-central1_gifs-website-prod;
        cd charts-prod && bash changeTagflask.sh
        cd charts-prod && kubectl apply -f service-html.yml;
        cd charts-prod && kubectl apply -f flask-prod.yml;
        sleep 60;
        cd charts-prod && bash updateHTML.sh;
        cd charts-prod && kubectl apply -f httpd-deploy-prod.yml;
        echo 'Deploy Application into Production GCP Cluster Completed';

    - name: Testing Prod-Server
      run: >
        cd Gifs-Website/tests && bash ingressIP.sh;
        cd Gifs-Website/tests && bash prod.sh;
        echo 'Testing Prod-Server Stage Completed';